"""M1 initial tables

Revision ID: 096efcc86413
Revises: 
Create Date: 2025-11-18 06:25:17.472386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096efcc86413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_ko', sa.String(length=255), nullable=True),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('summary_ko', sa.Text(), nullable=False),
    sa.Column('graph_cache', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    with op.batch_alter_table('Article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Article_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Article_original_url'), ['original_url'], unique=True)

    op.create_table('Concept',
    sa.Column('concept_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_ko', sa.Text(), nullable=False),
    sa.Column('real_world_examples_ko', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('concept_id')
    )
    with op.batch_alter_table('Concept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Concept_name'), ['name'], unique=True)

    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=True)

    op.create_table('Article_Concept',
    sa.Column('ac_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['Article.article_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['Concept.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ac_id')
    )
    with op.batch_alter_table('Article_Concept', schema=None) as batch_op:
        batch_op.create_index('idx_article_concept', ['article_id', 'concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Article_Concept_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Article_Concept_concept_id'), ['concept_id'], unique=False)

    op.create_table('Concept_Relation',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_concept_id', sa.Integer(), nullable=False),
    sa.Column('to_concept_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_concept_id'], ['Concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['Concept.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relation_id')
    )
    with op.batch_alter_table('Concept_Relation', schema=None) as batch_op:
        batch_op.create_index('idx_concept_relation', ['from_concept_id', 'to_concept_id'], unique=False)
        batch_op.create_index('idx_from_concept', ['from_concept_id'], unique=False)
        batch_op.create_index('idx_strength', ['strength'], unique=False)
        batch_op.create_index('idx_to_concept', ['to_concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Concept_Relation_from_concept_id'), ['from_concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Concept_Relation_to_concept_id'), ['to_concept_id'], unique=False)

    op.create_table('User_Collection',
    sa.Column('collection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['Concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='user_concept_UNIQUE')
    )
    with op.batch_alter_table('User_Collection', schema=None) as batch_op:
        batch_op.create_index('idx_user_collection', ['user_id', 'concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_Collection_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_Collection_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_Collection_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User_Collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_Collection_user_id'))
        batch_op.drop_index(batch_op.f('ix_User_Collection_concept_id'))
        batch_op.drop_index(batch_op.f('ix_User_Collection_collected_at'))
        batch_op.drop_index('idx_user_collection')

    op.drop_table('User_Collection')
    with op.batch_alter_table('Concept_Relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Concept_Relation_to_concept_id'))
        batch_op.drop_index(batch_op.f('ix_Concept_Relation_from_concept_id'))
        batch_op.drop_index('idx_to_concept')
        batch_op.drop_index('idx_strength')
        batch_op.drop_index('idx_from_concept')
        batch_op.drop_index('idx_concept_relation')

    op.drop_table('Concept_Relation')
    with op.batch_alter_table('Article_Concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Article_Concept_concept_id'))
        batch_op.drop_index(batch_op.f('ix_Article_Concept_article_id'))
        batch_op.drop_index('idx_article_concept')

    op.drop_table('Article_Concept')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    with op.batch_alter_table('Concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Concept_name'))

    op.drop_table('Concept')
    with op.batch_alter_table('Article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Article_original_url'))
        batch_op.drop_index(batch_op.f('ix_Article_created_at'))

    op.drop_table('Article')
    # ### end Alembic commands ###
